services:
  web:
    container_name: web-facturacion
    image: web-facturacion:latest 
    ports:
      - "8081:8080"
    depends_on:
      - api
  api:
    container_name: api-facturacion
    image: api-facturacion:latest
    env_file:
      - ./Server/.env.prod
    ports:
      - "42069:42069"
    depends_on:
      - db
  db:
    container_name: "facturacion-db-test"
    image: mysql:8.0.44-debian
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: facturacion
      MYSQL_USER: facturacion
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - "./database/mysql-data:/var/lib/mysql"
    restart: unless-stopped

