FROM  node:20-alpine AS deps
RUN apk add --no-cache libc6-compat openssl
WORKDIR /app

# Install Prisma Client - remove if not using Prisma

COPY prisma ./

# Install dependencies based on the preferred package manager

COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml\* ./

RUN \
    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
    elif [ -f package-lock.json ]; then npm ci; \
    elif [ -f pnpm-lock.yaml ]; then npm install -g pnpm && pnpm i; \
    else echo "Lockfile not found." && exit 1; \
    fi

##### BUILDER

FROM  node:20-alpine AS builder
WORKDIR /app
ARG DATABASE_URL
ARG SALT_ROUNDS 
ARG JWT_SECRET
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV SKIP_ENV_VALIDATION=1

RUN \
	if [ -f yarn.lock ]; then SKIP_ENV_VALIDATION=1 yarn prisma generate; \
    elif [ -f package-lock.json ]; then SKIP_ENV_VALIDATION=1 npm prisma generate; \
    elif [ -f pnpm-lock.yaml ]; then SKIP_ENV_VALIDATION=1 npm install -g pnpm &&  pnpm prisma generate; \
    else echo "Lockfile not found." && exit 1; \
    fi


RUN \
    if [ -f yarn.lock ]; then SKIP_ENV_VALIDATION=1 yarn build; \
    elif [ -f package-lock.json ]; then SKIP_ENV_VALIDATION=1 npm run build; \
    elif [ -f pnpm-lock.yaml ]; then npm install -g pnpm && SKIP_ENV_VALIDATION=1 pnpm run build; \
    else echo "Lockfile not found." && exit 1; \
    fi
##### RUNNER
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN apk add --no-cache openssl
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
COPY --from=builder /app/prisma ./prisma
EXPOSE 42069
CMD ["node", "dist/src/index.js"]
