ARG NODE_VERSION=24.11.1-alpine

FROM node:${NODE_VERSION} AS base
# Set working directory
WORKDIR /app

# Create non-root user for security
RUN addgroup -g 1001 -S nodejs && \
    adduser -S nodejs -u 1001 -G nodejs && \
    chown -R nodejs:nodejs /app

COPY package*.json ./

RUN npm ci 

COPY . .

RUN npm run build

USER nodejs

EXPOSE 42069

CMD [ "npm", "run", "start" ]
